name: Fix code styling

on:
  workflow_call:
    inputs:
      message:
        default: Fix code styling
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1

      - name: Install Prettier
        run: npm install prettier
        
      - name: Run Prettier
        run: npx prettier --write src
          
      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ inputs.message }}
